AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ContactFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/app.handler
      Runtime: nodejs16.x
      CodeUri: .
      Environment:
        Variables:
          TABLE_NAME: ContactSubmissions
      Events:
        ContactApi:
          Type: Api
          Properties:
            Path: /contact
            Method: post
  ContactTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ContactSubmissions
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
